
def countBase(sequence):
	a = g = c = t = 0
	for char in sequence:
		if char == 'A':
			a += 1
		if char == 'G':
			g += 1 
		if char == 'C':
			c += 1
		if char == 'T':
			t += 1;
	return {'A' : a, 'G' : g, 'C' : c, 'T' : t}

def countBasePairs(sequence):
	bases = {}
	nucleotides = ['A', 'T', 'C', 'G']
	for base in nucleotides:
		for base2 in nucleotides:
			bases[base + base2] = 0


def printBases(bases): 
	for key, value in bases.items():
		print(key, ": ", value)

sequence = "ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGA"

printBases(countBase(sequence))
